name: talab
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.6
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  awesome_dio_interceptor: any
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1

  cupertino_icons: ^1.0.2
  multi_select_flutter: ^4.1.3
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  image_picker: ^0.8.9
  permission_handler: ^10.4.3
  equatable: ^2.0.5
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.6
  light: ^3.0.1
  email_validator: ^2.1.17
  slide_to_act: ^2.0.2
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  mockito: ^5.4.2
  mocktail: ^0.3.0
  printing: ^5.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

fonts:
  - family: manrope-check
    fonts:
      - asset: fonts/manrope/Manrope-Bold.ttf
  - family: sf-italic
    fonts:
      - asset: fonts/SF/SFPRODISPLAYBLACKITALIC.OTF
  - family: sf-bold
    fonts:
      - asset: fonts/SF/SFPRODISPLAYBOLD.OTF
  - family: sf-medium
    fonts:
      - asset: fonts/SF/SFPRODISPLAYMEDIUM.OTF
  - family: sf-regular
    fonts:
      - asset: fonts/SF/SFPRODISPLAYREGULAR.OTF
  - family: sf-semibold
    fonts:
      - asset: fonts/SF/SF-Pro-Display-Semibold.otf
